### ISSUE TITLE
index and retrive source of the post

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/tattle-api#5]
Is there a way to filter the response based on author of the post?

lets say we use two services to index media - 
1. a whatsapp bot that scrapes data from whatsapp groups
2. a web scraper that scrapes data from fact checking websites

on the portal we have a way to differentiate source. since each user/bot has a user id, we are able to (with some granularity) say where a post originated from. 

so if lets say index a media item, its doc_id and its user_id, can i query tattle-api like this - send me doc ids of all media that is similar to this image AND that was inded by user_id X?

is this possible in its current iteration? and if not, can we support this?

**Comment by swairshah** [comment]
We do not have it yet but its not difficult to add. I can take it up next week.

**Comment by dennyabrain** [comment]
great. btw feel free to delegate to @kmjoshi ? i have a feeling that i want to explore a few tweaks to the search API as i am playing around with the search UI. so getting a handle on this would be useful. tell me if setting up a session just to discuss this with you and keshav makes sense.
